### ISSUE TITLE
Ensure that dependencies are setup before systems

### ISSUE THREAD

**Issue by Luminighty** [Luminighty/luminight-ecs#1]
Maybe add an `initSytems` function to the world. 

This could also be a non-issue though, since we probably will have dependencies before systems are added.
If that's the case, do some documentation and logging if we're accessing unavailable dependencies.

**Comment by Luminighty** [comment]
```
MissingDependencyError: Dependency DeltaTime not found! Have you initialized it?
    at DependencyContainer.get (/home/luminight/projects/luminight-ecs/dist/dependency/container.js:15:19)
    at World.getDependency (/home/luminight/projects/luminight-ecs/dist/world/world.js:64:34)
    at /home/luminight/projects/luminight-ecs/example.js:48:21
    at World.addSystem (/home/luminight/projects/luminight-ecs/dist/world/world.js:49:20)
    at Object.<anonymous> (/home/luminight/projects/luminight-ecs/example.js:47:7)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  key: [class DeltaTime]
}
```
